SELECT '##DBNAME##', tablekind, creatorname, tablename from dbc.tables WHERE (TABLEKIND = 'T' OR TABLEKIND = 'V') and DatabaseName = '##DBNAME##';

--split

SELECT
'##DBNAME##',
TABLENAME,
COLUMNNAME,
TRIM(COLUMNTYPE)||'('||TRIM(COLUMNNUM)||')'
FROM (
SELECT
DATABASENAME,
TABLENAME,
COLUMNNAME,
CASE WHEN COLUMNTYPE='CF' THEN 'CHAR'
     WHEN COLUMNTYPE='CV' THEN 'VARCHAR'
     WHEN COLUMNTYPE='D' THEN 'DECIMAL'
     WHEN COLUMNTYPE='TS' THEN 'TIMESTAMP'
     WHEN COLUMNTYPE='I' THEN 'INTEGER'
     WHEN COLUMNTYPE='I2' THEN 'SMALLINT'
     WHEN COLUMNTYPE='DA' THEN 'DATE'
END AS COLUMNTYPE,
CASE WHEN COLUMNTYPE='CF' THEN COLUMNLENGTH
     WHEN COLUMNTYPE='CV' THEN COLUMNLENGTH
     WHEN COLUMNTYPE='D' THEN (DECIMALTOTALDIGITS||','||DECIMALFRACTIONALDIGITS)
     WHEN COLUMNTYPE='TS' THEN COLUMNLENGTH
     WHEN COLUMNTYPE='I' THEN DECIMALTOTALDIGITS
     WHEN COLUMNTYPE='I2' THEN DECIMALTOTALDIGITS
     WHEN COLUMNTYPE='DA' THEN NULL
END AS COLUMNNUM
FROM DBC.COLUMNS
WHERE DATABASENAME='##DBNAME##' ) TBL;

--split

SELECT '##DBNAME##', creatorname, tablename, TABLEKIND  from dbc.tables WHERE (TABLEKIND = 'P' OR TABLEKIND = 'V' OR TABLEKIND = 'T') and DatabaseName = '##DBNAME##';

--split

SHOW PROCEDURE ##DBNAME##.##PROCEDURENAME##;

--split

SHOW TABLE ##DBNAME##.##TABLENAME##;

--split

SHOW VIEW ##DBNAME##.##VIEWNAME##;

